exit 1 on curl failure

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -25,9 +25,14 @@ touch $CACHE_DIR/test123
 # TODO: Md5
 # TODO: s3
 WEBAPP_RUNNER_URL="http://repo1.maven.org/maven2/com/github/jsimone/webapp-runner/$WEBAPP_RUNNER_VERSION/webapp-runner-$WEBAPP_RUNNER_VERSION.jar"
-echo -n "-----> Installing webapp-runner $WEBAPP_RUNNER_VERSION....."
+echo -n "-----> Installing webapp-runner $WEBAPP_RUNNER_VERSION... "
 curl --fail --silent --location $WEBAPP_RUNNER_URL > webapp-runner.jar
-echo " done"
+if [ $? == 0 ]; then
+  echo "done"
+else
+  echo "failed"
+  exit 1
+fi
 
 if [ ! -f Procfile ]; then
   cat > Procfile <<EOF
